---
- name: Install git
  apt: pkg=git state=installed update_cache=true

- name: Install command-line interpreter for php5
  apt: pkg=php5-cli state=installed

- name: Install zip command
  apt: pkg=zip state=installed update_cache=true

- name: Install pandoc
  apt: pkg=pandoc state=installed

- name: Install Sphinx user profile
  template: src=bash_profile.j2 dest=/home/sphinx/.bash_profile owner=sphinx group=sphinx

- name: Install TYPO3 management scripts
  copy: src=scripts dest=/home/sphinx owner=sphinx group=sphinx mode=0755

- name: Register Sphinx configuration
  template: src=scripts/etc/sphinx.conf.j2 dest=/home/sphinx/scripts/etc/sphinx.conf owner=sphinx group=sphinx

- name: Install Sphinx rendering configuration
  template: src=scripts/etc/LocalConfiguration.php.j2 dest=/home/sphinx/scripts/etc/LocalConfiguration.php owner=sphinx group=sphinx

- name: Install TYPO3 theme for Sphinx
  pip: name=t3SphinxThemeRtd virtualenv={{ sphinx_virtualenv }}

- name: Install directive t3-field-list-table for Sphinx
  pip: name=t3fieldlisttable virtualenv={{ sphinx_virtualenv }}

- name: Install directive ref-targets-list for Sphinx
  pip: name=t3targets virtualenv={{ sphinx_virtualenv }}

- name: Install Sphinx extension to transform table-row
  pip: name=t3tablerows virtualenv={{ sphinx_virtualenv }}

- name: Install TYPO3 theme for LaTeX
  copy: src=texmf/ dest=/usr/local/share/texmf

- name: Make font conversion script executable
  file: path=/usr/local/share/texmf/sources/typo3-share/convert-share.sh mode=0755

- name: Install TYPO3 Share font for LaTeX
  shell: /usr/local/share/texmf/sources/typo3-share/convert-share.sh

- name: Create directory for Git clones ({{ sphinx_git_directory }})
  file: path={{ sphinx_git_directory }} state=directory owner=sphinx group=sphinx

- name: Create directory for documentation projects ({{ doc_projects }})
  file: path={{ doc_projects }} state=directory owner=sphinx group=sphinx
