---
- name: Create a sphinx user
  user: name=sphinx comment="Sphinx server admin" system=no state=present home=/home/sphinx createhome=yes shell=/bin/bash

- name: Create directory for Sphinx
  file: path={{ sphinx_virtualenv }} state=directory

- name: Install pip
  apt: pkg=python-pip state=installed
  register: pipinstalled

- name: Set up the virtual environment
  pip: name=virtualenv
  when: pipinstalled|success
  register: virtualenvinstalled

- name: Install Sphinx v{{ sphinx_version }}
  pip: name=Sphinx version={{ sphinx_version }} virtualenv={{ sphinx_virtualenv }}
  when: virtualenvinstalled

- name: Install Mercurial
  apt: pkg=mercurial state=installed

- name: Fetch Sphinx extensions
  hg: repo=https://bitbucket.org/xperseguers/sphinx-contrib dest={{ sphinx_virtualenv }}/sphinx-contrib

- name: Install sphinxcontrib.googlechart
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/googlechart && sudo {{ sphinx_virtualenv }}/bin/python setup.py install

- name: Install sphinxcontrib.googlemaps
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/googlemaps && sudo {{ sphinx_virtualenv }}/bin/python setup.py install

- name: Install sphinxcontrib.httpdomain
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/httpdomain && sudo {{ sphinx_virtualenv }}/bin/python setup.py install

- name: Install sphinxcontrib.numfig
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/numfig && sudo {{ sphinx_virtualenv }}/bin/python setup.py install

- name: Install sphinxcontrib.slide
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/slide && sudo {{ sphinx_virtualenv }}/bin/python setup.py install

- name: Install sphinxcontrib.youtube
  shell: cd {{ sphinx_virtualenv }}/sphinx-contrib/youtube && sudo {{ sphinx_virtualenv }}/bin/python setup.py install
