---
- name: Install TeX Live base components
  apt: pkg=texlive-base state=installed update_cache=true

- name: Install TeX Live recommended packages for LaTeX
  apt: pkg=texlive-latex-recommended state=installed

- name: Install TeX Live extra packages for LaTeX
  apt: pkg=texlive-latex-extra state=installed

- name: Install TeX Live recommended fonts
  apt: pkg=texlive-fonts-recommended state=installed

- name: Install TeX Live extra fonts
  apt: pkg=texlive-fonts-extra state=installed

- name: Install make command
  apt: pkg=make state=installed
